apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: my-nginx
spec:
  ports:
    - nodePort: 32158
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: my-nginx
